app/config/AppConfig.scala, app/views/components/phaseBanner.scala.html, app/views/layouts/Layout.scala.html, conf/application.conf, conf/messages, conf/messages.cy, it/controllers/IndexControllerISpec.scala
=> [NOSTORY-BETA-BANNER] Added Beta banner

app/controllers/IndexController.scala, app/viewmodels/SummaryCardHelper.scala, app/views/components/summaryCard.scala.html, conf/messages, conf/messages.cy, it/controllers/IndexControllerISpec.scala, test/assets/messages/IndexMessages.scala, test/base/SpecBase.scala, test/viewmodels/IndexPageHelperSpec.scala, test/viewmodels/SummaryCardHelperSpec.scala, test/views/IndexViewSpec.scala, test/views/components/SummaryCardSpec.scala
- Only show financial penalty number when the financial penalty does not exceed the threshold
- Refactoring of some minor things
=> [PRM-208] - Reindex non-removed points

app/config/AppConfig.scala, app/viewmodels/SummaryCard.scala, app/viewmodels/SummaryCardHelper.scala, app/views/components/summaryCard.scala.html, conf/application.conf, conf/messages, test/assets/messages/IndexMessages.scala, test/base/SpecBase.scala, test/viewmodels/SummaryCardHelperSpec.scala, test/views/IndexViewSpec.scala
=> [PRM-217]: updated link for un-submitted return plus app conf changes

app/controllers/ComplianceController.scala, app/viewmodels/CompliancePageHelper.scala, app/viewmodels/IndexPageHelper.scala, app/views/ComplianceView.scala.html, conf/app.routes, conf/messages, conf/messages.cy, it/controllers/ComplianceControllerISpec.scala, test/assets/messages/ComplianceMessages.scala, test/base/BaseSelectors.scala, test/controllers/ComplianceControllerSpec.scala, test/controllers/IndexControllerSpec.scala, test/viewmodels/CompliancePageHelperSpec.scala, test/viewmodels/IndexPageHelperSpec.scala, test/views/ComplianceViewSpec.scala
Timeline addition and implementation is introduced in PRM-255
=> [PRM-259] - Compliance base view - without timeline

app/views/layouts/Layout.scala.html, conf/application.conf
=> [COOKIE_CONSENT] - Added cookie consent

app/models/point/AppealStatusEnum.scala, app/viewmodels/SummaryCardHelper.scala, conf/messages, conf/messages.cy, test/base/SpecBase.scala, test/models/point/AppealStatusEnumSpec.scala, test/viewmodels/SummaryCardHelperSpec.scala, test/views/components/SummaryCardSpec.scala
Financial point - met threshold
Normal point:
=> [PRM-385] - Show under tribunal review for tribunal review appeals

app/views/components/summaryCard.scala.html, test/views/components/SummaryCardSpec.scala
=> [PRM-FixAcceptedAppealPointNumber] - Removed point number when the appeal was successful

app/viewmodels/IndexPageHelper.scala, conf/messages, conf/messages.cy, test/assets/messages/IndexMessages.scala, test/viewmodels/IndexPageHelperSpec.scala
=> [PRM-397]: updated LSP expiry text

app/controllers/ComplianceController.scala, app/viewmodels/IndexPageHelper.scala, app/views/ComplianceView.scala.html, app/views/IndexView.scala.html, app/views/components/Header.scala.html, app/views/layouts/GovUkPageLayout.scala.html, build.sbt, conf/messages, conf/messages.cy, it/controllers/IndexControllerISpec.scala, it/stubs/AuthStub.scala, test/assets/messages/IndexMessages.scala, test/base/SpecBase.scala, test/viewmodels/IndexPageHelperSpec.scala, test/views/ComplianceViewSpec.scala, test/views/IndexViewSpec.scala
=> [PRM-402] - Added agent messages

app/views/IndexView.scala.html, test/views/IndexViewSpec.scala
=> [PRM-419] - Removed breadcrumb link for agents

app/viewmodels/SummaryCardHelper.scala, test/viewmodels/SummaryCardHelperSpec.scala, test/views/IndexViewSpec.scala, test/views/components/LatePaymentPenaltySummaryCardSpec.scala, test/views/components/LateSubmissionPenaltySummaryCardSpec.scala
=> [PRM-415] - Remove link to view message when user is agent

app/viewmodels/LatePaymentPenaltySummaryCard.scala, app/viewmodels/SummaryCardHelper.scala, app/views/components/summaryCardLPP.scala.html, it/controllers/IndexControllerISpec.scala, test/base/SpecBase.scala, test/viewmodels/SummaryCardHelperSpec.scala, test/views/IndexViewSpec.scala
AT PR: https://github.com/hmrc/penalties-acceptance-tests/pull/43
=> [PRM-436] - Added 'Check if you can appeal' for unpaid LPP VAT

app/controllers/IndexController.scala, app/models/ETMPPayload.scala, app/services/PenaltiesService.scala, app/viewmodels/IndexPageHelper.scala, app/views/IndexView.scala.html, conf/messages, conf/messages.cy, it/controllers/IndexControllerISpec.scala, it/stubs/PenaltiesStub.scala, test/base/SpecBase.scala, test/services/PenaltiesServiceSpec.scala, test/viewmodels/IndexPageHelperSpec.scala, test/views/IndexViewSpec.scala
=> [PRM-507] - Added late VAT list element

app/services/PenaltiesService.scala, app/viewmodels/IndexPageHelper.scala, conf/messages, conf/messages.cy, it/controllers/IndexControllerISpec.scala, test/services/PenaltiesServiceSpec.scala, test/viewmodels/IndexPageHelperSpec.scala
=> [PRM-512] - other unrelated penalties text

app/services/PenaltiesService.scala, app/viewmodels/IndexPageHelper.scala, conf/messages, conf/messages.cy, it/controllers/IndexControllerISpec.scala, test/services/PenaltiesServiceSpec.scala, test/viewmodels/IndexPageHelperSpec.scala
=>  [PRM-509] - Add (estimated) late payment penalties on call to action

app/viewmodels/SummaryCardHelper.scala, conf/messages, conf/messages.cy, test/assets/messages/IndexMessages.scala, test/base/SpecBase.scala, test/viewmodels/SummaryCardHelperSpec.scala
This reverts commit 83626d5b8651bcdf9b5da70351e4bff51dd89517.
=> Revert "PRM-532 Display 'ESTIMATED' tag"

app/viewmodels/TimelineHelper.scala, app/views/ComplianceView.scala.html, conf/messages, it/controllers/ComplianceControllerISpec.scala, test/assets/messages/ComplianceMessages.scala, test/viewmodels/TimelineHelperSpec.scala, test/views/ComplianceViewSpec.scala
=> [PRM-536]: added agent wording for compliance view

app/viewmodels/IndexPageHelper.scala, conf/messages, conf/messages.cy, test/assets/messages/IndexMessages.scala, test/viewmodels/IndexPageHelperSpec.scala
=> [PRM-243-Fix] - Added agent content for unpaid VAT on LPP tab

app/controllers/CalculationController.scala, app/controllers/IndexController.scala, app/services/PenaltiesService.scala, app/views/CalculationView.scala.html, app/views/IndexView.scala.html, app/views/components/summaryCardLPP.scala.html, conf/app.routes, conf/messages, conf/messages.cy, it/controllers/CalculationControllerISpec.scala, test/controllers/CalculationControllerSpec.scala, test/controllers/IndexControllerSpec.scala, test/services/PenaltiesServiceSpec.scala, test/views/CalculationViewSpec.scala, test/views/IndexViewSpec.scala, test/views/components/LatePaymentPenaltySummaryCardSpec.scala
=> [PRM-576] - Added amount received row to calculation table

app/controllers/CalculationController.scala, app/viewmodels/CalculationPageHelper.scala, app/viewmodels/SummaryCardHelper.scala, app/views/CalculationView.scala.html, conf/messages, conf/messages.cy, it/controllers/CalculationControllerISpec.scala, test/controllers/CalculationControllerSpec.scala, test/models/reason/PaymentPenaltyReasonEnumSpec.scala, test/viewmodels/CalculationPageHelperSpec.scala, test/viewmodels/SummaryCardHelperSpec.scala, test/views/CalculationViewSpec.scala
=> [PRM-575] - Added calculation row

app/controllers/CalculationController.scala, app/views/CalculationAdditionalView.scala.html, it/controllers/CalculationControllerISpec.scala, test/views/CalculationViewSpec.scala
=> PRM-584 Added Additional Penalty Rate

app/controllers/CalculationController.scala, app/viewmodels/CalculationPageHelper.scala, app/views/CalculationAdditionalView.scala.html, conf/messages, it/controllers/CalculationControllerISpec.scala, test/viewmodels/CalculationPageHelperSpec.scala, test/views/CalculationViewSpec.scala
=> [PRM-585] -  Add calculation row for additional penalties

app/controllers/CalculationController.scala, app/viewmodels/CalculationPageHelper.scala, app/views/CalculationLPPView.scala.html, conf/messages, it/controllers/CalculationControllerISpec.scala, test/assets/messages/CalculationMessages.scala, test/views/CalculationViewSpec.scala
=> [PRM-598] - Add period to LPP calculation screen

app/controllers/CalculationController.scala, app/viewmodels/CalculationPageHelper.scala, it/controllers/CalculationControllerISpec.scala, test/viewmodels/CalculationPageHelperSpec.scala
=> [PRM-602] - Refactored BigDecimal helper to always parse big decimals as 2dp

app/controllers/CalculationController.scala, app/views/CalculationAdditionalView.scala.html, app/views/CalculationLPPView.scala.html, it/controllers/CalculationControllerISpec.scala, test/views/CalculationViewSpec.scala
=> PRM-622 Added row 'Amount received'

app/controllers/CalculationController.scala, it/controllers/CalculationControllerISpec.scala
No AT changes required, so good to merge after review.
=> [PRM-627] Updated financial due date to use period instead

app/services/PenaltiesService.scala, app/viewmodels/IndexPageHelper.scala, it/controllers/IndexControllerISpec.scala, test/base/SpecBase.scala, test/connectors/PenaltiesConnectorSpec.scala, test/controllers/CalculationControllerSpec.scala, test/controllers/IndexControllerSpec.scala, test/services/PenaltiesServiceSpec.scala, test/viewmodels/IndexPageHelperSpec.scala
=> [PRM-628] Separated Call to Action Rows using Estimated/Due status

app/views/CalculationAdditionalView.scala.html, it/controllers/CalculationControllerISpec.scala, it/testUtils/IntegrationSpecCommonBase.scala, test/views/CalculationViewSpec.scala
=> [PRM-850] - Changed table to summary list for LPP additional calc view

app/views/components/Header.scala.html, test/views/IndexViewSpec.scala
https://user-images.githubusercontent.com/53828896/143065099-ac379854-7ca4-4dff-b628-7017b695b229.mov
=> [PRM-847] - Added GOV.UK link for GOV.UK logo

conf/messages, conf/messages.cy, test/assets/messages/IndexMessages.scala, test/services/PenaltiesServiceSpec.scala, test/views/IndexViewSpec.scala
=> [PRM-840] - Change service name for VAT traders

app/viewmodels/IndexPageHelper.scala, conf/messages, conf/messages.cy, test/viewmodels/IndexPageHelperSpec.scala
~Doesn't pass AT's~
https://github.com/hmrc/penalties-acceptance-tests/pull/119
=> [PRM-1010] - Used fixed penalty amount for fixed penalty messages

app/config/AppConfig.scala, app/views/CalculationAdditionalView.scala.html, app/views/CalculationLPPView.scala.html, app/views/ComplianceView.scala.html, app/views/layouts/Layout.scala.html, conf/application.conf, conf/messages, conf/messages.cy, test/assets/messages/IndexMessages.scala, test/views/CalculationViewSpec.scala, test/views/ComplianceViewSpec.scala, test/views/IndexViewSpec.scala
Compliance:
Home:
LPP Calc:
Additional Calc:
=> [PRM-1076] - Revised breadcrumb links

app/views/IndexView.scala.html, conf/messages, conf/messages.cy, it/controllers/IndexControllerISpec.scala, test/views/IndexViewSpec.scala
AT PR: https://github.com/hmrc/penalties-acceptance-tests/pull/121
=> [PRM-1087] - Removed 'Overview' from WYO section

app/config/AppConfig.scala, conf/application.conf
https://github.com/hmrc/app-config-base/pull/6774
=> [PRM-1102] - Use different config value for BTA link

app/views/components/summaryCardLPP.scala.html, it/controllers/IndexControllerISpec.scala, test/views/IndexViewSpec.scala, test/views/components/LatePaymentPenaltySummaryCardSpec.scala
=> [PRM-1123] - Moved 'View calculation' link to footer

app/viewmodels/SummaryCardHelper.scala, app/views/components/summaryCardLPP.scala.html, app/views/components/summaryCardLSP.scala.html, it/controllers/IndexControllerISpec.scala, test/base/BaseSelectors.scala, test/viewmodels/SummaryCardHelperSpec.scala, test/views/IndexViewSpec.scala, test/views/components/LateSubmissionPenaltySummaryCardSpec.scala
=> [PRM-1115]: Modified LSP and LPP summary card header and footer

app/views/CalculationLPPView.scala.html, conf/messages, conf/messages.cy, it/controllers/CalculationControllerISpec.scala, test/assets/messages/CalculationMessages.scala, test/base/BaseSelectors.scala, test/views/CalculationViewSpec.scala
=> [PRM-1162]: updated calculation page with new header

app/views/CalculationAdditionalView.scala.html, conf/messages, conf/messages.cy, it/controllers/CalculationControllerISpec.scala, test/assets/messages/CalculationMessages.scala, test/base/BaseSelectors.scala, test/views/CalculationViewSpec.scala
=> [PRM-1161] Updated heading in CalculationAdditionalView

app/views/components/timeline.scala.html, scalastyle-config.xml, test/assets/messages/ComplianceMessages.scala, test/viewmodels/TimelineHelperSpec.scala, test/views/ComplianceViewSpec.scala, test/views/components/TimelineSpec.scala
=> [PRM-1202] - Updated compliance view timeline rows

app/views/ComplianceView.scala.html, conf/messages, conf/messages.cy, test/assets/messages/ComplianceMessages.scala, test/views/ComplianceViewSpec.scala
=> [PRM-947] Added link on compliance view

app/views/components/Header.scala.html, app/views/layouts/GovUkPageLayout.scala.html, conf/messages, conf/messages.cy
Missing Welsh content on summary card due to content change pending
=> [PRM-1253] - Added Welsh excluding compliance + calculation pages

app/utils/ImplicitDateFormatter.scala, app/viewmodels/CalculationPageHelper.scala, app/viewmodels/SummaryCardHelper.scala, conf/messages, conf/messages.cy, test/base/SpecBase.scala, test/utils/ImplicitDateFormatterSpec.scala
=> [PRM-1266] - Added Welsh dates

app/models/v3/lpp/LPPDetails.scala, app/viewmodels/v2/LatePaymentPenaltySummaryCard.scala, app/viewmodels/v2/SummaryCardHelper.scala, app/views/components/v2/summaryCardLPP.scala.html, it/stubs/PenaltiesStub.scala, test/base/SpecBase.scala, test/models/v3/GetPenaltyDetailsSpec.scala, test/models/v3/lpp/LPPDetailsSpec.scala, test/models/v3/lpp/LatePaymentPenaltySpec.scala, test/viewmodels/v2/IndexPageHelperSpec.scala, test/viewmodels/v2/SummaryCardHelperSpec.scala, test/views/components/v2/LatePaymentPenaltySummaryCardSpec.scala
=> [PRM-1319] - Send penaltyChargeReference to appeals service for LPP

app/config/AppConfig.scala, app/config/featureSwitches/FeatureSwitch.scala, app/config/featureSwitches/FeatureSwitching.scala, app/controllers/IndexController.scala, app/controllers/testOnly/FeatureSwitchController.scala, conf/application.conf, conf/testOnlyDoNotUseInAppConf.routes, test/config/featureSwitches/FeatureSwitchSpec.scala, test/controllers/testOnly/FeatureSwitchControllerSpec.scala
Use either CURL or config value to set feature switch
=> [PRM-1365] - Revised feature switch implementation

app/viewmodels/v2/SummaryCardHelper.scala, conf/messages, conf/messages.cy, test/services/PenaltiesServiceSpec.scala, test/utils/MessagesSpec.scala
Updated some messages, added initial spec as well as checking if an English message is the same as a Welsh message (indicating it has not been translated - excluding some irrelevant ones)
=> [PRM-1381] - Added Welsh unit tests

app/assets/stylesheets/application.scss, app/controllers/CalculationController.scala, app/models/v3/lpp/LPPPenaltyCategoryEnum.scala, app/viewmodels/v2/LatePaymentPenaltySummaryCard.scala, app/viewmodels/v2/SummaryCardHelper.scala, app/views/CalculationAdditionalView.scala.html, app/views/CalculationLPPView.scala.html, app/views/components/v2/summaryCardLPP.scala.html, conf/app.routes, it/connectors/PenaltiesConnectorISpec.scala, it/controllers/CalculationControllerISpec.scala, test/controllers/CalculationControllerSpec.scala, test/models/v3/lpp/LPPPenaltyCategoryEnumSpec.scala, test/viewmodels/v2/SummaryCardHelperSpec.scala, test/views/components/v2/LatePaymentPenaltySummaryCardSpec.scala
Update calculation page caption as well due to lib upgrade
=> [PRM-1422] - Updated calculation controller to use principal charge reference and penalty category

app/views/CalculationLPP2View.scala.html, conf/messages, conf/messages.cy, it/controllers/CalculationControllerISpec.scala, test/assets/messages/CalculationMessages.scala, test/views/CalculationViewSpec.scala
=> [PRM-1616] - Changed 'Second late payment penalty' to 'Late payment penalty'

app/controllers/IndexController.scala, app/viewmodels/IndexPageHelper.scala, it/controllers/IndexControllerISpec.scala, test/controllers/IndexControllerSpec.scala, test/viewmodels/IndexPageHelperSpec.scala
Reverts hmrc/penalties-frontend#230
=> Revert "[PRM-1631] Call obligation API when user is at threshold"

app/controllers/IndexController.scala, app/viewmodels/IndexPageHelper.scala, it/controllers/IndexControllerISpec.scala, test/viewmodels/IndexPageHelperSpec.scala
Instead of looking at all LPP's, I wrote it to look at the first LPP to see if a TTP has been applied and is still active
=> [PRM-1720] - Added TTP handling to show content

app/views/layouts/Layout.scala.html, test/assets/messages/CalculationMessages.scala, test/assets/messages/ComplianceMessages.scala, test/assets/messages/IndexMessages.scala, test/views/CalculationViewSpec.scala, test/views/IndexViewSpec.scala
=> [PRM-1781] - Fixed agent title text

app/views/ErrorTemplate.scala.html, app/views/errors/Unauthorised.scala.html, app/views/layouts/Layout.scala.html
=> [PRM-1845] - Removed breadcrumbs and back links from error pages

app/controllers/IndexController.scala, app/viewmodels/IndexPageHelper.scala, it/controllers/IndexControllerISpec.scala, test/viewmodels/IndexPageHelperSpec.scala
=> [PRM-1850] - Hide penalties that have expired

app/controllers/IndexController.scala, app/viewmodels/IndexPageHelper.scala, it/controllers/IndexControllerISpec.scala, test/viewmodels/IndexPageHelperSpec.scala
AT's pass on old working branch
=> [PRM-1897] - added sorting of penalty points in descending order

app/views/components/summaryCardLSP.scala.html, test/views/ComplianceViewSpec.scala
=> [PRM-1898] - Resolved removed financial points not being handled correctly

.gitignore, app/services/PenaltiesService.scala, app/viewmodels/IndexPageHelper.scala, conf/messages, conf/messages.cy, it/controllers/IndexControllerISpec.scala, test/services/PenaltiesServiceSpec.scala, test/viewmodels/IndexPageHelperSpec.scala
Agent x1:
Trader x1:
Agent >1:
Trader >1:
=> [PRM-2080] - Added bullet point for amount of LPPs to WYO

app/config/featureSwitches/FeatureSwitch.scala, app/controllers/IndexController.scala, app/services/PenaltiesService.scala, app/viewmodels/IndexPageHelper.scala, app/views/IndexView.scala.html, conf/messages, conf/messages.cy, it/controllers/IndexControllerISpec.scala, test/config/featureSwitches/FeatureSwitchSpec.scala, test/config/featureSwitches/FeatureSwitchingSpec.scala, test/controllers/testOnly/FeatureSwitchControllerSpec.scala, test/services/PenaltiesServiceSpec.scala, test/viewmodels/IndexPageHelperSpec.scala, test/views/IndexViewSpec.scala
=> PRM-2095 Removed old WYO code

app/views/IndexView.scala.html, test/views/IndexViewSpec.scala
=> [PRM-2150] Set 'Contents', 'LSP', and 'LPP' to h3

app/views/components/summaryCardLPP.scala.html, app/views/components/summaryCardLSP.scala.html, it/controllers/IndexControllerISpec.scala, test/base/BaseSelectors.scala, test/views/components/LatePaymentPenaltySummaryCardSpec.scala, test/views/components/LateSubmissionPenaltySummaryCardSpec.scala
=> [PRM-2151] Set summary cards from h3 headings to h4

app/viewmodels/IndexPageHelper.scala, it/controllers/IndexControllerISpec.scala, test/viewmodels/IndexPageHelperSpec.scala
Requires the following PRs also
https://github.com/hmrc/penalties-acceptance-tests/pull/224
https://github.com/hmrc/penalties-stub/pull/82
=> PRM-2076 Filter NAT + NLT

app/views/IndexView.scala.html, conf/messages, conf/messages.cy, it/controllers/IndexControllerISpec.scala, test/assets/messages/IndexMessages.scala
=> [PRM-2203] - Moved 'Penalty and appeal details' out of WYO section

conf/messages.cy
=> [PRM-2251] Changed CThEM (HMRC) to CThEF in the Welsh Message

app/viewmodels/IndexPageHelper.scala
AT PR to go with change https://github.com/hmrc/penalties-acceptance-tests/pull/236
=> PRM-2262 edited penalty order logic to account for blank spaces

app/viewmodels/BreathingSpaceHelper.scala, test/viewmodels/BreathingSpaceHelperSpec.scala
=> [PRM-2208] - Added check for breathing space

app/viewmodels/SummaryCardHelper.scala, app/views/components/summaryCardLPP.scala.html, conf/messages, conf/messages.cy, test/views/components/LatePaymentPenaltySummaryCardSpec.scala
Needs stub data change and AT's
=> [PRM-2309] - Use principalChargeLatestClearing as indicator for VAT being paid

app/controllers/CalculationController.scala, app/viewmodels/CalculationPageHelper.scala, app/views/CalculationLPP2View.scala.html, conf/messages, conf/messages.cy, it/controllers/CalculationControllerISpec.scala, test/assets/messages/CalculationMessages.scala, test/utils/MessagesSpec.scala, test/viewmodels/CalculationPageHelperSpec.scala, test/views/CalculationViewSpec.scala
=> [PRM-2314] - Add TTP information to calculation pages

app/viewmodels/SummaryCardHelper.scala, app/views/components/summaryCardLSP.scala.html, conf/messages, conf/messages.cy, test/views/components/LateSubmissionPenaltySummaryCardSpec.scala
The Welsh translation for "Penalty" is needed,
=> Prm 2337 " Adjusted appealed penalty card logic"

app/viewmodels/IndexPageHelper.scala, app/viewmodels/WhatYouOweContent.scala, app/views/IndexView.scala.html, test/viewmodels/IndexPageHelperSpec.scala, test/views/IndexViewSpec.scala
Needs AT's
Nothing owed:
Owing:
=> [PRM-2404] - Hide 'check amounts and pay' button when nothing is owed

app/views/CalculationLPP1View.scala.html, app/views/CalculationLPP2View.scala.html
=> [PRM-2453] - Changed heading to xl on calculation pages

app/views/components/summaryCardLPP.scala.html, conf/messages, conf/messages.cy, it/controllers/IndexControllerISpec.scala, test/views/components/LatePaymentPenaltySummaryCardSpec.scala
Waiting for welsh before putting up for review
=> PRM-2586 Added hidden text to avoid duplicate headings on LPP

app/viewmodels/LateSubmissionPenaltySummaryCard.scala, app/viewmodels/SummaryCardHelper.scala, app/views/components/summaryCardLSP.scala.html, conf/messages, conf/messages.cy, test/viewmodels/SummaryCardHelperSpec.scala, test/views/components/LateSubmissionPenaltySummaryCardSpec.scala
Stub data to test against https://github.com/hmrc/penalties-stub/pull/116
=> PRM-1618 Added content for removed points + made logic work with sample data

app/controllers/CalculationController.scala, app/models/lpp/LPPDetails.scala, app/utils/PagerDutyHelper.scala, app/viewmodels/CalculationPageHelper.scala, it/controllers/CalculationControllerISpec.scala, test/controllers/testOnly/FeatureSwitchControllerSpec.scala, test/models/lpp/LPPDetailsSpec.scala, test/models/lpp/LatePaymentPenaltySpec.scala, test/viewmodels/CalculationPageHelperSpec.scala
Implements both PRM-2722 / PRM-2723 to prevent conflicts
=> [PRM-2722/2723] - Handle scenario where TTPStartDate or TTPEndDate is not present

app/config/AppConfig.scala, app/controllers/SignOutController.scala, app/views/components/Header.scala.html, app/views/errors/Unauthorised.scala.html, app/views/layouts/Layout.scala.html, conf/app.routes, conf/application.conf, test/controllers/SignOutControllerSpec.scala, test/views/components/HeaderSpec.scala
Config PR: https://github.com/hmrc/app-config-base/pull/8988
=> [PRM-2747] - Link to feedback page when user signs out

app/controllers/IndexController.scala, app/models/lpp/LPPDetails.scala, it/controllers/IndexControllerISpec.scala, test/base/testData/LPPDetailsTestData.scala, test/models/lpp/LPPDetailsSpec.scala
=> PRM-2743 Add ordering to LPPDetails

app/viewmodels/SummaryCardHelper.scala, conf/messages, conf/messages.cy, project/plugins.sbt, test/assets/messages/IndexMessages.scala
=> [PRM-2899] - Remove HTML from messages file
